# Generated by Django 3.1.5 on 2021-07-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_meeting_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='code',
        ),
    ]
