# Generated by Django 3.1.5 on 2021-07-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_meeting_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('User', models.CharField(max_length=100)),
            ],
        ),
    ]
