# Generated by Django 3.1.5 on 2021-07-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_meetingjoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingjoin',
            name='owner',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
