# Generated by Django 3.1.5 on 2021-07-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_meetingjoin_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='Meeting',
            field=models.CharField(max_length=100),
        ),
    ]
